import typescriptPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import importPlugin from 'eslint-plugin-import';

export default [
    {
        ignores: ['./dist/db/migrations/*.js', './src/db/migrations/*.ts'],
    },
    {
        files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: 'module',
            parser: tsParser,
            globals: {
                require: 'readonly',
                module: 'readonly',
                process: 'readonly',
                setTimeout: 'readonly',
                __dirname: 'readonly',
            },
        },
        plugins: {
            '@typescript-eslint': typescriptPlugin,
            import: importPlugin,
        },
        rules: {
            'eqeqeq': 'warn',
            'no-console': 'off',
            'no-undef': 'off',
            'no-invalid-this': 'error',
            'no-return-assign': 'error',
            'no-unused-expressions': ['error', { allowTernary: true }],
            'no-useless-concat': 'error',
            'no-useless-return': 'error',
            'no-constant-condition': 'warn',
            'semi': 'error',
            'semi-spacing': 'error',
            'quotes': ['error', 'single'],
            'indent': ['error', 4, { SwitchCase: 1 }],
            'space-before-blocks': 'error',
            'space-in-parens': 'error',
            'space-infix-ops': 'error',
            'space-unary-ops': 'error',
            'keyword-spacing': 'error',
            'multiline-ternary': ['error', 'never'],
            'no-mixed-operators': 'error',
            'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
            'no-mixed-spaces-and-tabs': 'warn',
            'no-whitespace-before-property': 'error',
            'nonblock-statement-body-position': 'error',
            'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
            'arrow-spacing': 'error',
            'no-confusing-arrow': 'error',
            'no-duplicate-imports': 'error',
            'no-var': 'error',
            'prefer-const': 'error',
            'prefer-template': 'warn',
            'object-shorthand': 'off',
            'max-len': ['error', { code: 350 }],
            'max-lines': ['error', { max: 600 }],
            'comma-dangle': ['error', 'always-multiline'],
            'object-curly-spacing': ['error', 'always'],
            'array-bracket-spacing': ['error', 'never'],
            'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
            'import/order': [
                'error',
                {
                    groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
                    'newlines-between': 'always',
                },
            ],
            'import/newline-after-import': ['error', { count: 1 }],
            '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: 'req|res|next|__' }],
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-inferrable-types': 'off',
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
            '@typescript-eslint/prefer-for-of': 'warn',
            '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
        },
    },
];